<?php
// $Id: xoops_version.php,v 1.1 2012/03/31 16:04:15 ohwada Exp $

//=========================================================
// Captcha Module
// 2007-02-18 K.OHWADA
//=========================================================

include_once XOOPS_ROOT_PATH.'/modules/captcha/include/version.php';

$modversion['name']        = _MI_CAPTCHA_NAME;
$modversion['description'] = _MI_CAPTCHA_DESC;
$modversion['version']  = CAPTCHA_VERSION;
$modversion['author']   = 'Kenichi OHWADA<br />( http://linux2.ohwada.net/ )';
$modversion['credits']  = '';
$modversion['help']     = "help.html";
$modversion['license']  = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image']    = 'images/captcha_slogo.png';
$modversion['dirname']  = 'captcha';

$modversion['cube_style'] = true;

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
//$modversion['sqlfile']['mysql'] = '';

// Tables created by sql file (without prefix!)
//$modversion['tables'][0] = '';

// Admin things
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu']  = "admin/menu.php";

// Menu
$modversion['hasMain'] = 0;
//$modversion['sub'][1]['name'] = '';
//$modversion['sub'][1]['url']  = '';

//  Search 
$modversion['hasSearch'] = 0;
//$modversion['search']['file'] = '';
//$modversion['search']['func'] = '';

// Blocks 
//$modversion['blocks'][1]['file']        = '';
//$modversion['blocks'][1]['name']        = '';
//$modversion['blocks'][1]['description'] = '';
//$modversion['blocks'][1]['show_func']   = '';
//$modversion['blocks'][1]['edit_func']   = '';
//$modversion['blocks'][1]['options']     = '';
//$modversion['blocks'][1]['template']    = ''';

// Templates
//$modversion['templates'][1]['file'] = '';
//$modversion['templates'][1]['description'] = '';

// Config
if (defined('LEGACY_BASE_VERSION') && version_compare(LEGACY_BASE_VERSION, '2.2.2.3', '>')) {
$modversion['config'] = array(
	array(
		'name'			=> 'registUser',
		'title'			=> '_MI_CAPTCHA_REGISTUSER' ,
		'description'	=> '_MI_CAPTCHA_REGISTUSER_DESC' ,
		'formtype'		=> 'yesno' ,
		'valuetype'		=> 'int' ,
		'default'		=> 0 ,
		'options'		=> array()
	) 
);
}
